### ISSUE TITLE
Add select for faculties in chat page

### ISSUE THREAD

**Issue by chewmanji** [Solvro/web-promochator#47]
ML team says that sending faculty may improve response's accuracy from model
I know it's not in design but it's not an issue, place it anywhere you think it won't destroy UX
### Name of faculties: 
"Faculty of Architecture",
"Faculty of Civil Engineering",
"Faculty of Chemistry",
"Faculty of Information and Communication Technology",
"Faculty of Electrical Engineering",
"Faculty of Geoengineering, Mining and Geology",
"Faculty of Environmental Engineering",
 "Faculty of Management",
"Faculty of Mechanical and Power Engineering",
"Faculty of Mechanical Engineering",
"Faculty of Fundamental Problems of Technology",
"Faculty of Electronics, Photonics and Microsystems",
"Faculty of Pure and Applied Mathematics",
"Faculty of Medicine"

Map it to object/enum.

**Comment by maciejkrol18** [comment]
I found few more things that should be addressed regarding the input bar in general

- suggested topics
![Image](https://github.com/user-attachments/assets/c4112e67-3a60-4903-b3a4-69a7c9070625)
- input allowing an empty prompt to be sent
- input not submitting when Enter is pressed (both in ChatGPT and Claude Enter submits, while Shift+Enter is used to create a new line)

We could either create new issues for each of those things or change this issue so that it covers the faculty selection + stuff mentioned above. What do you think? @chewmanji

**Comment by chewmanji** [comment]
> * suggested topics

I don't think we can implement this so that it'd be anyhow useful  - I've thought about adding a tooltip that would suggest user how to write a good prompt (but that's not neccessary for now)

> * input allowing an empty prompt to be sent

I've tried to wrap this component with form and use Zod and React-hook-form to handle this but I couldn't figure out how to do this properly 😭

> * input not submitting when Enter is pressed (both in ChatGPT and Claude Enter submits, while Shift+Enter is used to create a new line)

I think it can be easily done with the tiptap editor so yeah, we can change it

> We could either create new issues for each of those things or change this issue so that it covers the faculty selection + stuff mentioned above.

You can do the last one in this issue as it's relatively simple, the first one is optional, the second one also can be easily implemented without form (and additional stuff) so as hotfix you can do this also
